{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.aspectj",
    "module": "aspectj-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1.jar",
          "url": "aspectj-plugin-1.0.0-beta1.jar",
          "size": 27531,
          "sha512": "7a3621c2a277f23fca443fa351223bd91c13671170dfeec0fd8e9e4e20f0360d7247b968a3f18237d66ddac81096e632fb417a5e426cef05a47393379bf80e4f",
          "sha256": "a25311af69c13b5eb1296214b8a4b3897457549bef11c8e000b6634423b0809a",
          "sha1": "0205ebc4712280777433f136200756eb8e79b4d2",
          "md5": "c0d74b3a0befce9e6f93e9e19d3fca63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjtools",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1.jar",
          "url": "aspectj-plugin-1.0.0-beta1.jar",
          "size": 27531,
          "sha512": "7a3621c2a277f23fca443fa351223bd91c13671170dfeec0fd8e9e4e20f0360d7247b968a3f18237d66ddac81096e632fb417a5e426cef05a47393379bf80e4f",
          "sha256": "a25311af69c13b5eb1296214b8a4b3897457549bef11c8e000b6634423b0809a",
          "sha1": "0205ebc4712280777433f136200756eb8e79b4d2",
          "md5": "c0d74b3a0befce9e6f93e9e19d3fca63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1-sources.jar",
          "url": "aspectj-plugin-1.0.0-beta1-sources.jar",
          "size": 5016,
          "sha512": "2dca7665e4ec0a61eeb788a4ea4a1e35e2bda0342a59903f439c213966877eda17237f0046dae9bea3e19cbb43296f97ccd5d9ae1496ea95ded9d8d4a2e91c98",
          "sha256": "a20c043f9dbacbc893858522d6de4208ff81024fed0a6edc0d46e9576ae498ca",
          "sha1": "a7fc5d574da0c233d2747f20726e9a25bd6435fb",
          "md5": "5d1a255525dbf72f88b5cdb7364aabef"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1-javadoc.jar",
          "url": "aspectj-plugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "9e34f569ffe3eacd7ef0ca7bf2a8650fb17fadfc7a68157049abbfbddaeb5bd0483a7822eb931852ac53845bb7d45ed62e9afbe0f7693610416ce10e015569c2",
          "sha256": "ca55e4a896281086b7c7c19e834305855304bd8a89c8fd30f4997535d1520ae2",
          "sha1": "e01f56619878afc5d2c6e99c79cafb641974b482",
          "md5": "43649ecbc7e82c407b028e5000afce1b"
        }
      ]
    }
  ]
}
