{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.aspectj",
    "module": "aspectj-plugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1.jar",
          "url": "aspectj-plugin-1.0.0-beta1.jar",
          "size": 27451,
          "sha512": "e1502815b40c761be9821e440b18242e380aaaecbde73d480ec902c762556f687784f54b8d1981b8177793b69d356e7bc553c7a71c5786cbf7bb1cbbb67e7ee1",
          "sha256": "7d347b1d02d72f1259d4d39c7d2695ecd08376a8369aab3b738f42e04b67785f",
          "sha1": "32c0f855b19ca885b6ccffb5fb417ae436b54a8b",
          "md5": "978cf76010e6da542f48406a079010a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjtools",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1.jar",
          "url": "aspectj-plugin-1.0.0-beta1.jar",
          "size": 27451,
          "sha512": "e1502815b40c761be9821e440b18242e380aaaecbde73d480ec902c762556f687784f54b8d1981b8177793b69d356e7bc553c7a71c5786cbf7bb1cbbb67e7ee1",
          "sha256": "7d347b1d02d72f1259d4d39c7d2695ecd08376a8369aab3b738f42e04b67785f",
          "sha1": "32c0f855b19ca885b6ccffb5fb417ae436b54a8b",
          "md5": "978cf76010e6da542f48406a079010a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1-sources.jar",
          "url": "aspectj-plugin-1.0.0-beta1-sources.jar",
          "size": 5015,
          "sha512": "b4cf984e924c82a29879369ac854df82f8fa5ac5651dc38d5e87e15125b7ee7a6d997a0aa433caaae7e097ce026f20a64697381f7028c02a53f2e05267420333",
          "sha256": "263daf6253901a692691959d1d7f1fcf53c887f2fb147d05eaf0975ec5979761",
          "sha1": "e2a2b3bca84310e206f134fb6ee977013978c27b",
          "md5": "9c8398aea55a9d4000650fb44803a1a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aspectj-plugin-1.0.0-beta1-javadoc.jar",
          "url": "aspectj-plugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "7b819ad5ed099a7aa89a2eee80e784818fbf7775587c531bab8f499679b74d98491bf71b5e8a929b07129f9621ad982c2d4eefbf11d57c0c51b228980212775f",
          "sha256": "c25b974a196a9f5b2e170bdafa46b861dda1c0238f8b77839b13029de6a96c5b",
          "sha1": "8e5f41b87015045894897ff9615a6d6d2bfcc80f",
          "md5": "f90401adbf116a2d8f8c7dd458fc82b8"
        }
      ]
    }
  ]
}
