{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.aspectj",
    "module": "AspectjPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 33979,
          "sha512": "af1bab1d4a5919b718e8b374c3a73b8278fc782bfd03012b9c21abedaf6d467601ff7d65f498b331bd67533f0a8c0ade8df5467ccf1dd86bae5b7d4fb8c86cfa",
          "sha256": "cdbdbfa5711f8f2facb26c8a0e74842696c3d1c2882414252ced4eb9ff432f29",
          "sha1": "b414ac6416b352dfcb31892117976fbee12496ba",
          "md5": "f34421b708dddd8626cf11d367dd3202"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.xiaojinzi.aspectj",
          "module": "aspectj-api",
          "version": {
            "requires": "1.0.0-beta1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjtools",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 33979,
          "sha512": "af1bab1d4a5919b718e8b374c3a73b8278fc782bfd03012b9c21abedaf6d467601ff7d65f498b331bd67533f0a8c0ade8df5467ccf1dd86bae5b7d4fb8c86cfa",
          "sha256": "cdbdbfa5711f8f2facb26c8a0e74842696c3d1c2882414252ced4eb9ff432f29",
          "sha1": "b414ac6416b352dfcb31892117976fbee12496ba",
          "md5": "f34421b708dddd8626cf11d367dd3202"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "url": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "size": 7341,
          "sha512": "9179795b04bd7d39b1070c6a0a772fceb222acd724151407cacc2c408ae59712f937e11141e82223aa18b77a45f081c6dd6563f0db31fa8ad3c5dcdd3026bf2f",
          "sha256": "8049b5f9d1d5b5d55411b85dd03857d02878e272334c1b05fc0e219508ea51e9",
          "sha1": "a24dbfaffe31e1d2c6a9279ed064db4d82e01b40",
          "md5": "7ee1e7979cc1bd6368c23ee8df5b0193"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "url": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "eb5ac1be386d837d427e3b3f55359df7a85ded961bd8ac3de14ef7c89f5a13bdaff06bfeab4e821dd2a1aa14e6d52d65ec8e80caaccadc4f7f146e31016605eb",
          "sha256": "e3383205487c69d9dccf01ba55d592d540bc384604975a86cffc91e3f82d6b1b",
          "sha1": "82f0e2f93eb71746fd8a41f7c799adf6c4329559",
          "md5": "ad0009de1ab04647e43323e348b37e17"
        }
      ]
    }
  ]
}
