{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.aspectj",
    "module": "AspectjPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 25892,
          "sha512": "7fb1d68539e6dc447782a5dcfa8c97b38c783c5d7953a6710270b88edaf3d3a1134ec5394cbf28f3bab9439233a3c43a6f2cd3bd79b74ea5b0635b715fb4c1a0",
          "sha256": "753f86c68059df1209f964572e5cd7b8c8da8568531180cc97b8eaeda34cbef5",
          "sha1": "d4037bae3807651aefe025f5554be5444c177fa6",
          "md5": "1703c3046b71abc2a3196d5aa9552b4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjtools",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 25892,
          "sha512": "7fb1d68539e6dc447782a5dcfa8c97b38c783c5d7953a6710270b88edaf3d3a1134ec5394cbf28f3bab9439233a3c43a6f2cd3bd79b74ea5b0635b715fb4c1a0",
          "sha256": "753f86c68059df1209f964572e5cd7b8c8da8568531180cc97b8eaeda34cbef5",
          "sha1": "d4037bae3807651aefe025f5554be5444c177fa6",
          "md5": "1703c3046b71abc2a3196d5aa9552b4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "url": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "size": 4840,
          "sha512": "b500e2b0e57a336d89e4104b658a2627d520423b19da7353473abf53d6fad66150371bdf4a3d85219780231dfe1634af6c389a6840fa8d40561876a628de9856",
          "sha256": "6d983d0f3235703379fcd8aaa7f7291b6ff8c130b283359f388b8593bb823ca8",
          "sha1": "b8131b935abaec73b7a62ffaa466d44b6e62660d",
          "md5": "2880fa854e5efcd369c61f5b3abe5d6b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "url": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "3216b27fec7b864e536d621260a83bf60e6d3f694dcce898a3088144ee502bf2697875dba0a0a269988a80909359c00390520e4b5c6ed9025e385692658a5ce0",
          "sha256": "012edaaea33ec02353c0426f15598f6967118aa12d1862911a855deaf84fad55",
          "sha1": "19b8980690e30c5fcae51c7fff724855aecbd317",
          "md5": "020ef4a414ee1e830b2997dc51c54e0e"
        }
      ]
    }
  ]
}
