{
  "formatVersion": "1.1",
  "component": {
    "group": "com.xiaojinzi.aspectj",
    "module": "AspectjPlugin",
    "version": "1.0.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 24400,
          "sha512": "23776ea219f10b7f5906e5189c049c2891bceeb6a2fc2ce17384ff28949654bbbf554f3056f4bb33096ce8134271560375db553db949e2b6c4237d4e6d4dca3a",
          "sha256": "80e73b6a2d234f203d35b7f93ac16ebdb18c4781fe562391f0d25ed3462803a2",
          "sha1": "902c24ad0681e7085a0b0b319a094465071e7c5d",
          "md5": "fcfb812fb9e233c7341549a26911023e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjtools",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1.jar",
          "url": "AspectjPlugin-1.0.0-beta1.jar",
          "size": 24400,
          "sha512": "23776ea219f10b7f5906e5189c049c2891bceeb6a2fc2ce17384ff28949654bbbf554f3056f4bb33096ce8134271560375db553db949e2b6c4237d4e6d4dca3a",
          "sha256": "80e73b6a2d234f203d35b7f93ac16ebdb18c4781fe562391f0d25ed3462803a2",
          "sha1": "902c24ad0681e7085a0b0b319a094465071e7c5d",
          "md5": "fcfb812fb9e233c7341549a26911023e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "url": "AspectjPlugin-1.0.0-beta1-sources.jar",
          "size": 4453,
          "sha512": "444094086a030527533843b2fb28c07e06557cd0235afb0c36996cd2344d9c714dbc74b91220b06f8b329c466fa5684c21218c8daa445121120e0759f781d6c3",
          "sha256": "7d09020df124eac3b8cc1a47f91fcf09bda489bb41bb7638997f99c68a752c0b",
          "sha1": "c79ad530485f1bd0a0f0c25dff7cd68b3c46daf0",
          "md5": "f4bdbe19e23e8b8f5f3990669adac6fe"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "url": "AspectjPlugin-1.0.0-beta1-javadoc.jar",
          "size": 261,
          "sha512": "c9726df4008d2ac2910e0b0e5ca336b42d47b53acd9a6c1f09ef2ee7b88508ee5212314c058ea2872f8476304aa3c63e94e05d2edb02bb8b4df0f76c4f06e77d",
          "sha256": "f29b99891853584433b6ddfaa6dbbd65dcc163f48de9116e80e6f4f2727ae88d",
          "sha1": "9ecec2c8d20af75b08e5c6472e6615611573b006",
          "md5": "6b4ac639e63b0edddfc7eb7624948f38"
        }
      ]
    }
  ]
}
